#!/usr/bin/env python3

import hashlib
import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RELEASE_ROOT = ROOT / "public-context" / "v1" / "preview-20260823-a"


class ExternalContextTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest = json.loads((RELEASE_ROOT / "manifest.json").read_text(encoding="utf-8"))

    def test_six_target_variant_documents_exist(self):
        records = self.manifest["documents"]
        self.assertEqual(6, len(records))
        self.assertEqual(
            {
                (target, variant)
                for target in ("dsp", "ui")
                for variant in ("instrument", "fx", "midi")
            },
            {(record["target"], record["variant"]) for record in records},
        )

    def test_documents_are_self_contained_and_receipts_are_document_only(self):
        manifest_text = (RELEASE_ROOT / "manifest.json").read_text(encoding="utf-8")
        self.assertNotIn("context_id", manifest_text)
        self.assertNotIn("end_token", manifest_text)

        for record in self.manifest["documents"]:
            with self.subTest(path=record["path"]):
                path = RELEASE_ROOT / record["path"]
                raw = path.read_bytes()
                text = raw.decode("utf-8")
                context_match = re.search(r"^CONTEXT_ID: (\S+)$", text, re.MULTILINE)
                end_match = re.search(r"^END_TOKEN: (\S+)$", text, re.MULTILINE)

                self.assertLess(len(raw), 30_000)
                self.assertNotIn(b"\x00", raw)
                self.assertNotIn("\r", text)
                self.assertNotIn("http://", text)
                self.assertNotIn("https://", text)
                self.assertTrue(text.startswith("AMORPH_EXTERNAL_CONTEXT v1\n"))
                self.assertEqual(1, text.count("BEGIN_AMORPH_CONTEXT"))
                self.assertEqual(1, text.count("END_AMORPH_CONTEXT"))
                self.assertIsNotNone(context_match)
                self.assertIsNotNone(end_match)
                body = text.split("BEGIN_AMORPH_CONTEXT\n", 1)[1].split(
                    "END_AMORPH_CONTEXT\n", 1
                )[0]
                body_sha = hashlib.sha256(body.encode("utf-8")).hexdigest()
                self.assertEqual(record["body_sha256"], body_sha)
                self.assertEqual(
                    f"amorph-{record['target']}-{record['variant']}-{body_sha[:16]}",
                    context_match.group(1),
                )
                self.assertEqual(f"amorph-end-{body_sha[-16:]}", end_match.group(1))
                self.assertTrue(text.endswith(f"END_TOKEN: {end_match.group(1)}\n"))
                self.assertIn("return exactly CONTEXT_UNAVAILABLE", text)
                self.assertIn("// AMORPH_CONTEXT_ID: <exact CONTEXT_ID>", text)
                self.assertIn("// AMORPH_END_TOKEN: <exact END_TOKEN>", text)
                self.assertEqual(record["bytes"], len(raw))
                self.assertEqual(record["document_sha256"], hashlib.sha256(raw).hexdigest())

    def test_editable_sources_are_not_generated_amorph_exports(self):
        for path in sorted((ROOT / "context-src" / "v1").glob("*/*.md")):
            with self.subTest(path=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertNotIn("GENERATED by export_paste_context.py", text)
                self.assertNotIn("Source: InfinityLab commit", text)

    def test_dsp_sources_cover_observed_generalised_failures(self):
        for path in sorted((ROOT / "context-src" / "v1" / "dsp").glob("*.md")):
            with self.subTest(path=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertIn("never declare a value with `let` inside a `for` or `while` body", text)
                self.assertIn("preserve every existing endpoint, parameter", text)
                self.assertIn("next sequential `paramN` ID", text)
                self.assertIn("a Cmajor state initializer is not a substitute", text)
                self.assertIn("preserves the existing intended/audible default", text)
                self.assertIn("After the two required receipt comments", text)
                self.assertNotIn("Inside the fence, start directly with", text)

    def test_ui_sources_require_one_parameter_marker_per_endpoint(self):
        for path in sorted((ROOT / "context-src" / "v1" / "ui").glob("*.md")):
            with self.subTest(path=path.name):
                text = path.read_text(encoding="utf-8")
                self.assertIn("exactly ONE DOM element with `data-param`", text)
                self.assertIn('querySelectorAll("[data-param]").length', text)
                self.assertIn("line 3", text)
                self.assertIn("After the two required receipt comments", text)
                self.assertNotIn("Inside the fence, start directly with", text)


if __name__ == "__main__":
    unittest.main()
