#!/usr/bin/env python3
"""Build self-contained plain-text context documents for Amorph Copy/Paste."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "context-src" / "v1"
DEFAULT_RELEASE = "preview-20260823-a"

TARGETS = ("dsp", "ui")
VARIANTS = ("instrument", "fx", "midi")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def normalise_source(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    text = text.replace("\r\n", "\n").replace("\r", "\n").strip() + "\n"
    if "\x00" in text:
        raise ValueError(f"NUL byte in {path}")
    if "GENERATED by export_paste_context.py" in text:
        raise ValueError(f"generated Amorph header remains in editable source {path}")
    return text


def response_contract(target: str) -> str:
    if target == "dsp":
        filename = "dsp.cmajor"
        fence = "cmajor"
        source_start = "The next source token must be graph or processor."
        handoff = "Amorph removes the outer fence before Compile."
    else:
        filename = "index.js"
        fence = "javascript"
        source_start = (
            "The next line must be `// WINDOW SIZE: <width>x<height>`. "
            "The next source token after that comment must be class or export."
        )
        handoff = "Amorph removes the outer fence before loading the UI."

    return f"""RESPONSE CONTRACT — REQUIRED

Return the complete corrected `{filename}` in exactly one fenced code block
tagged `{fence}`. Return no prose, heading, explanation, or second code block.
Do not use SEARCH/REPLACE blocks, patches, ellipses, or placeholders.

The first two lines inside the fence must copy the exact receipt values printed
near the top and bottom of this document:

// AMORPH_CONTEXT_ID: <exact CONTEXT_ID>
// AMORPH_END_TOKEN: <exact END_TOKEN>

{source_start} {handoff}
"""


def render_document(target: str, variant: str, source: str, release: str) -> tuple[str, dict]:
    body = response_contract(target).strip() + "\n\n" + source.strip() + "\n"
    body_sha = sha256_text(body)
    context_id = f"amorph-{target}-{variant}-{body_sha[:16]}"
    end_token = f"amorph-end-{body_sha[-16:]}"

    document = f"""AMORPH_EXTERNAL_CONTEXT v1
CONTEXT_ID: {context_id}
TARGET: {target}
VARIANT: {variant}
RELEASE: {release}
BODY_SHA256: {body_sha}
CONTENT_TYPE: text/plain; charset=utf-8
ACCESS_CONTRACT: anonymous complete-document retrieval; no secondary URL required
FAILURE_CONTRACT: return exactly CONTEXT_UNAVAILABLE when retrieval is incomplete

BEGIN_AMORPH_CONTEXT
{body.rstrip()}
END_AMORPH_CONTEXT
END_TOKEN: {end_token}
"""

    metadata = {
        "target": target,
        "variant": variant,
        "path": f"{target}/{variant}.txt",
        "body_sha256": body_sha,
        "document_sha256": sha256_text(document),
        "bytes": len(document.encode("utf-8")),
    }
    return document, metadata


def build(release: str, output_root: Path, check: bool) -> int:
    release_root = output_root / "v1" / release
    records = []
    mismatches = []

    for target in TARGETS:
        for variant in VARIANTS:
            source = normalise_source(SOURCE_ROOT / target / f"{variant}.md")
            document, metadata = render_document(target, variant, source, release)
            destination = release_root / target / f"{variant}.txt"
            records.append(metadata)

            if check:
                if not destination.exists() or destination.read_text(encoding="utf-8") != document:
                    mismatches.append(str(destination.relative_to(ROOT)))
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(document, encoding="utf-8")

    manifest = {
        "schema_version": 1,
        "release": release,
        "content_type": "text/plain; charset=utf-8",
        "documents": records,
    }
    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    manifest_path = release_root / "manifest.json"

    if check:
        if not manifest_path.exists() or manifest_path.read_text(encoding="utf-8") != manifest_text:
            mismatches.append(str(manifest_path.relative_to(ROOT)))
        if mismatches:
            print("Generated context is stale:")
            for path in mismatches:
                print(f"  {path}")
            return 1
    else:
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(manifest_text, encoding="utf-8")

    print(f"PASS: {len(records)} self-contained context documents for {release}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--release", default=DEFAULT_RELEASE)
    parser.add_argument("--output-root", type=Path, default=ROOT / "public-context")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return build(args.release, args.output_root.resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
